### ISSUE TITLE
Coding longitudinal data

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/wrangling-phenotype#11]
For longitudinal data do we want to add a column, e.g. date_of_scan, to enable potential matching with other variables later? Or, age could be used a proxy?

**Comment by htwangtw** [comment]
What's the label in the original dataset? Age would be more relevant to the analysis so I think that would be fine. We can bring this up in the meeting

**Comment by clarkenj** [comment]
ADNI and CIMA-Q have both a date and a visit name coded (e.g. V10, bl). OASIS uses age_at_entry and then days from entry (e.g. d0129) for each visit. OK!

**Comment by htwangtw** [comment]
Ahhh yeah it's going to be hard to find a way to standardise this across dataset. We will need some brain storming

**Comment by clarkenj** [comment]
Adding notes from meeting here:
- We will use the age variable to code longitudinal data, based on data provided from study.
- Can iterate if does not seem to be effective.
